server:
  port:  # ?? ??

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:33306/ecommerce?serverTimezone=Asia/Seoul
    username: hhuser
    password: hh99pw
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create  # create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false


#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
logging:
  level:
    com.example.orderservice: DEBUG
